version: '3.8'

services:
  backend:
    container_name: backend
    networks:
      - service-tier
      - front-tier
      - db-tier
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - MONGO_CONN=mongodb://mongo-db:27017
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
      - /app/node_modules
    depends_on:
      - neo4j

  frontend:
    container_name: frontend
    networks:
      - front-tier
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - /app/packages/frontend/node_modules
      - /app/packages/shared/node_modules
      - /app/node_modules
    depends_on:
      - backend

  neo4j:
    image: neo4j:5.6.0-enterprise
    networks:
      - db-tier
    container_name: neo4j-db
    ports:
      - 7888:7474 # HTTP
      - 7999:7687 # Bolt
      - 2004:2004
    environment:
      - NEO4J_AUTH=neo4j/password
      #- NEO4J_dbms_memory_pagecache_size=1G
      #- NEO4J_dbms_memory_heap_initial__size=1G
      #- NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_EDITION=docker_compose
      - EXTENDED_CONF=yes
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs


  mongo-db:
    image: mongo:latest
    networks:
      - db-tier
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    container_name: mongo-express
    networks:
      - db-tier
    depends_on:
      - mongo-db
    ports:
      - "8888:8081"


volumes:
  neo4j_data:
  neo4j_logs:
  mongo-data:

networks:
  service-tier:
  front-tier:
  db-tier: