services:
  mongo-db:
    extends:
      file: ./docker-compose.templates.yml
      service: database
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    profiles: [ "databases" ]
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    networks:
      - db-tier
    depends_on:
      - mongo-db
    ports:
      - "8888:8081"

  neo4j-db:
    image: neo4j:5.6.0-enterprise
    extends:
      file: ./docker-compose.templates.yml
      service: database
    container_name: neo4j-db
    ports:
      - 7888:7474
      - 7999:7687
      - 2004:2004
    volumes:
      - neo4j-data:/data
      - ./neo4j/logs:/var/lib/neo4j/logs
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      #- type: bind
      #  source: ./neo4j/conf
      #  target: /var/lib/neo4j/conf
      #  bind:
      #    propagation: shared
      - ./neo4j/metrics:/var/lib/neo4j/metrics
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/backups:/var/lib/neo4j/backups
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_EDITION: docker_compose
      EXTENDED_CONF: 'yes'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]

  nats-service:
    extends:
      file: ./docker-compose.templates.yml
      service: transport
    container_name: nats-service
    image: nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222


  service-core:
    extends:
      file: ./docker-compose.templates.yml
      service: service
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    container_name: service-core
    command: pnpm run start:dev service-core

  gateway:
    extends:
      file: ./docker-compose.templates.yml
      service: gateway-service
    container_name: gateway
    environment:
      PORT: 5000
    command: pnpm run start:dev gateway
    ports:
      - 5001:5000

  frontend:
    extends:
      file: ./docker-compose.templates.yml
      service: frontend
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    environment:
      PORT: 5173
      API_DOMAIN: http://gateway:5000
      SOCKET_DOMAIN: http://127.0.0.1:5001
      NODE_ENV: development
      HOST_IP: ${HOST_IP}
      GATEWAY_PORT: 5000
    ports:
      - 5173:5173
      # - 8002:8002

volumes:
  mongo-data:
  neo4j-data:

networks:
  service-tier:
    external: true
  front-tier:
    external: true
  db-tier:
    external: true
